Create users
panagiotismak/Skroutz_Lists pull request #1
Opened 2017-07-16 13:40 UTC by panagiotismak

2017-07-16 14:05 UTC, filippiazikou requested changes

2017-07-16 14:05 UTC, filippiazikou commented on app/controllers/users_controller.rb
> +  	else
Fix indentation here

2017-07-16 14:05 UTC, filippiazikou commented on app/controllers/users_controller.rb
> +      render 'new'
Do you want to flash an error message here maybe?

2017-07-16 14:05 UTC, filippiazikou commented on app/models/user.rb
> +  before_save { self.email = email.downcase }
empty line after `before_save`

2017-07-16 14:05 UTC, filippiazikou commented on app/models/user.rb
> +  has_secure_password
change lines for readability

2017-07-16 14:11 UTC, panagiotismak commented on app/models/user.rb
> +  before_save { self.email = email.downcase }
done

2017-07-16 14:11 UTC, panagiotismak commented on app/models/user.rb
> +  has_secure_password
done

2017-07-16 14:13 UTC, panagiotismak commented on app/controllers/users_controller.rb
> +  	else
not valid

2017-07-17 09:41 UTC, panagiotismak commented
@filippiazikou take a look again

2017-07-17 18:13 UTC, filippiazikou commented
Do you need all these images on git?

2017-07-17 18:56 UTC, filippiazikou approved these changes
Congrats :D !!

2017-07-17 18:56 UTC, filippiazikou commented on app/controllers/sessions_controller.rb
> +  	  flash[:danger] = "There was something wrong with your login information. Please Try again"
indentation

2017-07-17 18:56 UTC, filippiazikou commented on app/controllers/users_controller.rb
> +  	else
indentation

2017-07-18 10:30 UTC, panagiotismak commented on app/controllers/sessions_controller.rb
> +  	  flash[:danger] = "There was something wrong with your login information. Please Try again"
done

2017-07-18 10:30 UTC, panagiotismak commented on app/controllers/users_controller.rb
> +  	else
done

2017-08-29 17:32 UTC, merged